source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target 'MovileExercicio', :exclusive => true do
  # Add Application pods here
  pod 'Argo'

end



